# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inconsistencies.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QHeaderView

from ui.models.tableModel import InconsistenciesTableModel


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(549, 311)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(Dialog)
        problems = [('E:\\MY Applications\\main.py', 'szf', 1024, 256), ("E:\\Folder 1", "ned"), ("E:\\Folder 2", "nrd", 34, 32)]
        self.tableModel = InconsistenciesTableModel(Dialog, inconsistencies=problems)
        self.verticalLayout.addWidget(self.tableView)
        self.tableView.setModel(self.tableModel)
        self.tableView.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        # self.tableView.verticalHeader().setSectionResizeMode(QHeaderView.ResizeToContents)
        # self.tableWidget = QtWidgets.QTableWidget(Dialog)
        # self.tableWidget.setObjectName("tableWidget")
        # self.tableWidget.setColumnCount(4)
        # self.tableWidget.setRowCount(2)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setVerticalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignCenter)
        # self.tableWidget.setHorizontalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignCenter)
        # self.tableWidget.setHorizontalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignCenter)
        # self.tableWidget.setHorizontalHeaderItem(2, item)
        # item = QtWidgets.QTableWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignCenter)
        # self.tableWidget.setHorizontalHeaderItem(3, item)
        # item = QtWidgets.QTableWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignCenter)
        # self.tableWidget.setItem(0, 0, item)
        # item = QtWidgets.QTableWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignCenter)
        # self.tableWidget.setItem(0, 1, item)
        # item = QtWidgets.QTableWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignCenter)
        # self.tableWidget.setItem(0, 2, item)
        # item = QtWidgets.QTableWidgetItem()
        # item.setTextAlignment(QtCore.Qt.AlignCenter)
        # self.tableWidget.setItem(0, 3, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setItem(1, 0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setItem(1, 1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setItem(1, 2, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setItem(1, 3, item)
        # self.verticalLayout.addWidget(self.tableWidget)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.acceptFileButton = QtWidgets.QPushButton(self.frame)
        self.acceptFileButton.setObjectName("acceptFileButton")
        self.horizontalLayout.addWidget(self.acceptFileButton)
        self.closeButton = QtWidgets.QPushButton(self.frame)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        # item = self.tableWidget.verticalHeaderItem(0)
        # item.setText(_translate("Dialog", "1"))
        # item = self.tableWidget.verticalHeaderItem(1)
        # item.setText(_translate("Dialog", "2"))
        # item = self.tableWidget.horizontalHeaderItem(0)
        # item.setText(_translate("Dialog", "Item Name"))
        # item = self.tableWidget.horizontalHeaderItem(1)
        # item.setText(_translate("Dialog", "Problem"))
        # item = self.tableWidget.horizontalHeaderItem(2)
        # item.setText(_translate("Dialog", "Old Size"))
        # item = self.tableWidget.horizontalHeaderItem(3)
        # item.setText(_translate("Dialog", "New Size"))
        # __sortingEnabled = self.tableWidget.isSortingEnabled()
        # self.tableWidget.setSortingEnabled(False)
        # item = self.tableWidget.item(0, 0)
        # item.setText(_translate("Dialog", "E:\\\\First"))
        # item = self.tableWidget.item(0, 1)
        # item.setText(_translate("Dialog", "Not Existing"))
        # item = self.tableWidget.item(0, 2)
        # item.setText(_translate("Dialog", "12,45 MB"))
        # item = self.tableWidget.item(0, 3)
        # item.setText(_translate("Dialog", "0"))
        # item = self.tableWidget.item(1, 0)
        # item.setText(_translate("Dialog", "Ceva"))
        # item = self.tableWidget.item(1, 1)
        # item.setText(_translate("Dialog", "Different Sizes"))
        # item = self.tableWidget.item(1, 2)
        # item.setText(_translate("Dialog", "12,55 GB"))
        # item = self.tableWidget.item(1, 3)
        # item.setText(_translate("Dialog", "3,54 GB"))
        # self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.acceptFileButton.setText(_translate("Dialog", "Accept"))
        self.closeButton.setText(_translate("Dialog", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
